---
Gráficos Básicos
---
Histograma
```{r}
trees
hist(trees$Height)
hist(trees$Height, main="Árvores", ylab="Frequência",xlab="Altura", col = "blue")
hist(trees$Height, main = "Árvores", ylab = "Frequência", xlab="Altura", col="blue", density = 20, breaks = 20)
```
Densidade
```{r}
densidade = density(trees$Height)
plot(densidade)
```
Densidade sobre o Histograma, parâmetro par
```{r}
#Executar com ctrl+shift+enter
hist(trees$Height, main = NULL, xlab = NULL, ylab = NULL, probability = T, xaxt ='n', yaxt='n')
par(new=TRUE)
plot(densidade)
```
Dispersão
```{r}
plot(trees$Girth, trees$Volume)
plot(trees$Girth, trees$Volume, main="Árvores")
plot(trees$Girth, trees$Volume, ylab = "Circunferência", xlab="Volume", col="blue", main="Árvores")
#pch muda o elemento gráfico
plot(trees$Girth, trees$Volume, ylab="Circunferência", xlab="Volume", col="blue", main="Árvores", pch=20)

```
Muda tipo
```{r}
plot(trees$Girth, trees$Volume, ylab="Circunferência", xlab="Volume", col="orange", main="Árvores", pch=20,  type="l")
```
Tremulação, diminui sobre posição
```{r}
plot(jitter(trees$Girth), trees$Volume, ylab = "Circunferência", xlab = "Volume", col="orange", main = "Árvores")
```
Legenda com Dimensão Categórica
```{r}
plot(CO2$conc, CO2$uptake, pch=20, col= CO2$Treatment)
# bottom, bottomleft, left, topleft, top, topright, right and center
legend("bottomright", legend = c("nonchilled", "chilled"), cex=1, fill = c("black", "red"))
```
Novos dados
```{r}
plot(trees)
```
Divisão da tela
```{r}
#Executar com ctrl + shift + enter
split.screen(figs=c(2,2))
screen(1)
plot(trees$Girth, trees$Volume)
screen(2)
plot(trees$Girth, trees$Height)
screen(3)
plot(trees$Height, trees$Volume)
screen(4)
hist(trees$Volume)
close.screen(all=TRUE)
```

Boxplot
```{r}
boxplot(trees$Volume, main="Árvores", xlab="Volume")
boxplot(trees$Volume, main="Árvores", xlab="Volume", col = "purple", horizontal = TRUE)
boxplot(trees$Volume, main="Árvores", xlab="Volume", col = "purple", outline = F)
```
```{r}
#Notch
boxplot(trees$Height, main="Árvores", xlab = "Altura", col = "red", notch = TRUE)
#dados do gráfico
boxplot.stats(trees$Height)
#lê apenas uma informação
boxplot.stats(trees$Height)$stats
```
Vários gráficos
```{r}
boxplot(trees)
```
Agregação
```{r}
InsectSprays
spray = aggregate(. ~ spray, data = InsectSprays, sum)
spray
```
Gráfico de Barras
```{r}
#Executar com ctrl + shift + enter
barplot(spray$count, col = gray.colors(6), xlab="Spray", ylab="Total", names.arg = spray$spray)
box()
```
Gráfico de Setor - Pizza
```{r}
pie(spray$count, labels = spray$spray, main = "Spray", col=c(1:6))
```
Pizza com legenda
```{r}
pie(spray$count, labels=NA, main = "Spray", col=c(1:6))
legend("bottomright", legend=spray$spray, cex=1, fill=c(1:6))
```


